export const S = {
  // Layout
  appBody: {
    fontFamily: "'IBM Plex Sans', sans-serif",
    background: "#F8FAFC",
    minHeight: "100vh",
    display: "flex",
  },
  sidebar: {
    width: 240,
    background: "#0F172A",
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    flexShrink: 0,
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },

  // Topbar
  topbar: {
    background: "white",
    borderBottom: "1px solid #F1F5F9",
    padding: "0 32px",
    height: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 10,
    boxShadow: "0 1px 0 #F1F5F9",
  },

  // Card
  card: {
    background: "white",
    border: "1px solid #F1F5F9",
    borderRadius: 12,
    boxShadow: "0 1px 4px rgba(15,23,42,0.04), 0 4px 16px rgba(15,23,42,0.04)",
  },
  cardHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid #F8FAFC",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#0F172A",
    letterSpacing: "-0.01em",
  },
  cardBody: { padding: 20 },

  // Stat card
  statCard: {
    background: "white",
    border: "1px solid #F1F5F9",
    borderRadius: 12,
    padding: "20px 24px",
    boxShadow: "0 1px 4px rgba(15,23,42,0.04), 0 4px 16px rgba(15,23,42,0.04)",
  },

  // Buttons
  btnPrimary: {
    background: "#6366F1",
    color: "white",
    borderRadius: 8,
    fontFamily: "'IBM Plex Sans',sans-serif",
    fontWeight: 600,
    fontSize: 13,
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    transition: "background 0.15s",
    letterSpacing: "-0.01em",
  },
  btnOutline: {
    background: "white",
    border: "1px solid #E2E8F0",
    color: "#475569",
    borderRadius: 8,
    fontFamily: "'IBM Plex Sans',sans-serif",
    fontWeight: 500,
    fontSize: 13,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    transition: "all 0.15s",
  },
  btnDanger: {
    background: "white",
    border: "1px solid #FECACA",
    color: "#DC2626",
    borderRadius: 8,
    fontFamily: "'IBM Plex Sans',sans-serif",
    fontWeight: 500,
    fontSize: 13,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
  },

  // Form
  formLabel: {
    fontSize: 12,
    fontWeight: 500,
    color: "#64748B",
    letterSpacing: "-0.01em",
  },
  formInput: {
    width: "100%",
    padding: "9px 12px",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    fontFamily: "'IBM Plex Sans',sans-serif",
    fontSize: 13,
    color: "#0F172A",
    background: "white",
    outline: "none",
    boxSizing: "border-box",
    transition: "border 0.15s",
  },
  formSection: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#94A3B8",
    margin: "20px 0 12px",
    paddingBottom: 8,
    borderBottom: "1px solid #F1F5F9",
  },
  filterInput: {
    padding: "7px 12px",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    fontFamily: "'IBM Plex Sans',sans-serif",
    fontSize: 13,
    color: "#374151",
    background: "white",
    outline: "none",
  },

  // Table
  th: {
    padding: "10px 16px",
    textAlign: "left",
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#94A3B8",
    whiteSpace: "nowrap",
    background: "#F8FAFC",
  },
  td: {
    padding: "12px 16px",
    borderBottom: "1px solid #F8FAFC",
    verticalAlign: "middle",
    fontSize: 13,
    color: "#334155",
  },

  // Modal
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.6)",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backdropFilter: "blur(4px)",
  },
  modalBox: {
    background: "white",
    borderRadius: 16,
    width: "90%",
    maxWidth: 520,
    boxShadow: "0 32px 80px rgba(15,23,42,0.25)",
    maxHeight: "90vh",
    overflowY: "auto",
    border: "1px solid #F1F5F9",
  },
  modalHeader: {
    padding: "20px 24px 16px",
    borderBottom: "1px solid #F8FAFC",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#0F172A",
    letterSpacing: "-0.02em",
  },
  modalBody: { padding: "20px 24px" },
  modalFooter: {
    padding: "14px 24px",
    borderTop: "1px solid #F8FAFC",
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
    background: "#FAFAFA",
    borderRadius: "0 0 16px 16px",
  },

  // Badges
  badgeActive: {
    background: "#ECFDF5",
    color: "#059669",
    border: "1px solid #A7F3D0",
  },
  badgeDiscontinued: {
    background: "#FFFBEB",
    color: "#D97706",
    border: "1px solid #FDE68A",
  },
  badgeGraduated: {
    background: "#EEF2FF",
    color: "#4F46E5",
    border: "1px solid #C7D2FE",
  },

  // Icon button
  iconBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 12,
    background: "white",
    color: "#64748B",
    transition: "all 0.15s",
  },
};
